import { Router } from "express";
import Productos from '../models/Productos';
import { createProductos, deleteProductos, renderEditProducto, renderProductos, statusProductos, updateProductos } from "../controllers/productoController";
import Proveedores from '../models/Proveedores';
import { createProveedor, deleteProveedor, renderEditProveedor, renderProveedores, statusProveedor, updateProveedor } from "../controllers/proveedoresController";
import { renderRegistro, registrarUsuario, renderLogin, loginUsuario, logoutUsuario} from "../controllers/authController";
import { verificarSesion } from "../middlewares/authMiddleware";
const router=Router();
router.get("/", (req, res) => {
    res.render("index");
});
router.get("/", (req, res) => {
    res.render("index");
});
router.get("/registro",renderRegistro);
router.post("/registro",registrarUsuario);
router.get("/login", renderLogin);
router.post("/login",loginUsuario);
router.get("/",logoutUsuario);
router.get("/productos",verificarSesion,renderProductos);
router.post("/productos/agregar",verificarSesion,createProductos);
router.get("/productos/:id/update",verificarSesion,renderEditProducto);
router.post("/productos/:id/update",verificarSesion,updateProductos);
router.get("/productos/:id/delete",verificarSesion,deleteProductos);
router.get("/productos/:id/status",verificarSesion,statusProductos);
router.get("/proveedores",verificarSesion,renderProveedores);
router.post("/proveedores/agregar",verificarSesion,createProveedor);
router.get("/proveedores/:id/update",verificarSesion,renderEditProveedor);
router.post("/proveedores/:id/update",verificarSesion,updateProveedor);
router.get("/proveedores/:id/delete",verificarSesion,deleteProveedor);
router.get("/proveedores/:id/status",verificarSesion,statusProveedor);
export default router;